import { CHANNELS, type DecisionEntry, type MediaPlan, type Pacing, type WeeklyReport } from './types';
import { addDays, cad, currentWeekIndex, dayMonth, lineName, paceAll, pct, weekStart } from './calc';

// Deterministic first drafts, written from the numbers. Nothing here is generated by a
// model, so nothing can be invented; the campaign manager edits the draft before sending.

const list = (xs: string[]) =>
  xs.length <= 1 ? xs.join('') : `${xs.slice(0, -1).join(', ')} and ${xs[xs.length - 1]}`;


export function draftHeadline(p: MediaPlan, pace: Pacing, r: WeeklyReport): string {
  const t = paceAll(p, pace);
  const onPace = t.pacing !== null && t.pacing >= pace.underPace && t.pacing <= pace.overPace;
  const perfOk = t.performanceCpa !== null && t.performanceCpa <= p.targetCpa;
  const delivery = onPace ? 'on pace' : t.pacing !== null && t.pacing > pace.overPace ? 'ahead of pace' : 'behind pace';
  return `Week ${r.number} in review: ${delivery}, ${p.conversionName}s ${perfOk ? 'ahead of' : 'behind'} plan in performance channels`;
}

export function draftSummary(p: MediaPlan, pace: Pacing, r: WeeklyReport): string[] {
  const t = paceAll(p, pace);
  const working = t.rows.filter((x) => x.line.role !== 'non_working' && x.status !== 'Held');
  const behind = working.filter((x) => x.status === 'Underpacing').map((x) => lineName(x.line));
  const ahead = working.filter((x) => x.status === 'Overpacing').map((x) => lineName(x.line));
  const onTrack = t.pacing !== null && t.pacing >= pace.underPace && t.pacing <= pace.overPace;

  const out: string[] = [];
  out.push(
    `**Delivery is ${onTrack ? 'on track' : t.pacing! > pace.overPace ? 'running ahead' : 'running behind'}.** The campaign has spent ${cad(t.spend)}, ${pct(t.pacing ?? 0)} of planned spend to date.` +
      (behind.length || ahead.length
        ? ` ${behind.length ? `${behind.length === 1 ? 'One line is' : `${behind.length} lines are`} behind (${list(behind)})` : 'No line is behind'}` +
          `${ahead.length ? ` and ${ahead.length === 1 ? 'one is' : `${ahead.length} are`} ahead (${list(ahead)})` : ''}; fixes are already live.`
        : ' Every line is inside the pacing band.')
  );

  if (t.performanceCpa !== null) {
    const diff = t.performanceCpa / p.targetCpa - 1;
    const perfRoles = [...new Set(t.rows.filter((x) => x.line.role === 'performance').map((x) => CHANNELS[x.line.channel].short.toLowerCase()))];
    const best = t.rows
      .filter((x) => x.line.role === 'performance' && x.cpa !== null)
      .sort((a, b) => a.cpa! - b.cpa!)
      .slice(0, 2)
      .map((x) => `${lineName(x.line)} at ${cad(x.cpa!, 2)}`);
    out.push(
      `**Performance channels are ${diff <= 0 ? 'beating' : 'missing'} the goal.** ${perfRoles.length > 3 ? 'Social, search, retail and display' : list(perfRoles)} are delivering ${p.conversionName}s at ${cad(t.performanceCpa, 2)}, ${pct(Math.abs(diff))} ${diff <= 0 ? 'under' : 'over'} the ${cad(p.targetCpa, 2)} target. ${list(best)} lead.`
    );
  }

  if (t.cpa !== null) {
    const awareness = t.rows.filter((x) => x.line.role === 'awareness').map((x) => CHANNELS[x.line.channel].short);
    out.push(
      t.cpa > p.targetCpa
        ? `**Blended CPA (${cad(t.cpa, 2)}) is above target, as planned for this stage.** ${list([...new Set(awareness)])} are awareness buys, and last-touch attribution undercounts them.`
        : `**Blended CPA (${cad(t.cpa, 2)}) is at or under the ${cad(p.targetCpa, 2)} target,** including the awareness lines.`
    );
  }

  const n = r.decisions.length;
  if (n) {
    const first = r.decisions[0].request.replace(/^Approve /, 'approve ');
    out.push(`**${n === 1 ? 'One decision' : `${n} decisions`} needed this week:** ${first}${n > 1 ? ', and more below' : ''}.`);
  }
  return out;
}

export function draftComingUp(p: MediaPlan, pace: Pacing): string[] {
  const now = currentWeekIndex(p, pace);
  const out: string[] = [];
  for (let i = now; i < Math.min(p.weeks.length, now + 3); i++) {
    const w = p.weeks[i];
    if (!w.moment && !w.weight) continue;
    const start = weekStart(p, i);
    out.push(`**Week ${i + 1} (${dayMonth(start)}–${dayMonth(addDays(start, 6))}):** ${w.moment || 'steady delivery'}, ${pct(w.weight)} of the budget.`);
  }
  out.push(`**Weekly status reports** continue every week until the flight ends on ${dayMonth(p.flightEnd)}, followed by the full post-campaign analysis.`);
  return out;
}

// "What we changed", written from the decision record for the reporting week: what
// was approved or applied automatically, each with the reason it was suggested and
// any note the manager left. Overruled suggestions are left out, because nothing
// changed; search-term changes are summarised rather than listed term by term.
export function draftChanges(p: MediaPlan, pace: Pacing, decisions: DecisionEntry[]): string[] {
  const from = addDays(pace.dataThrough, -6);
  const week = decisions.filter((d) => d.date >= from && d.date <= pace.dataThrough && d.ruling !== 'overruled' && d.ruling !== 'shadow');
  const out: string[] = [];
  for (const d of week.filter((d) => d.kind !== 'search_term')) {
    const how = d.ruling === 'auto' ? 'applied automatically as a routine change' : 'approved by the campaign manager';
    out.push(`**${d.subject}:** ${d.action.toLowerCase()}, ${how}. ${d.why ? `${d.why.charAt(0).toUpperCase()}${d.why.slice(1)}.` : ''}${d.note ? ` ${d.note.trim().replace(/[^.!?]$/, '$&.')}` : ''}`.trim());
  }
  const terms = week.filter((d) => d.kind === 'search_term');
  if (terms.length) {
    const byAction = new Map<string, number>();
    for (const d of terms) byAction.set(d.action, (byAction.get(d.action) ?? 0) + 1);
    out.push(`**Search terms:** ${terms.length} reviewed by the campaign manager (${[...byAction].map(([a, n]) => `${n} × ${a.toLowerCase()}`).join(', ')}).`);
  }
  return out;
}
